### ISSUE TITLE
Update default branch to be `trunk`

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/doaction.org#11]
Based on https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/ The default branch should be updated to trunk.

I'm not aware of how this is deployed and if it relies on the branch name. @hlashbrooke, maybe you know? Or maybe you know who would know? 

If you someone else wants to do it, the steps I've been doing are:

1. Create `trunk` from `master`
2. on the settings/branches page, change the default
3. Update existing pull requests to point to `trunk`
4. Delete master with `git push origin --delete master`

**Comment by hlashbrooke** [comment]
Thanks for the ping @aaronjorbin. Fortunately, this repo doesn't actually deploy to the live site just yet, so changing to a new branch name is easy enough without any negative ramifications. I'll sort that out this week.

**Comment by hlashbrooke** [comment]
This has been done.
