### ISSUE TITLE
Missing events in the "Past Events" page

### ISSUE THREAD

**Issue by naokomc** [WordPress/doaction.org#13]
The "past events" pages are not listing all events.
https://doaction.org/past-events/
https://doaction.org/ja/past-events/

I didn't check through all of the events, but none of these three most recent events that happened in 2023 are listed.
- [Barcelona](https://doaction.org/es/event/barcelona-2023/)
- [Anceu](https://doaction.org/event/ruralhackers/)
- [Granada](https://doaction.org/es/event/granada-2023/)

<img width="1371" alt="Screenshot 2023-06-30 at 11 14 41" src="https://github.com/WordPress/doaction.org/assets/34067/cab6ca63-661a-4d2e-8975-93ee7634a534">

**Comment by StevenDufresne** [comment]
The code is looking for the event to be "completed" which is a manual action when viewing the post. Not sure why that would be the case?
https://github.com/WordPress/doaction.org/blob/e95e9d88012aa1a1f9d448ec70995219c254a10a/wp-content/plugins/do-action/includes/class-do-action.php#L983C18-L983C27

I have "completed" the Barcelona event and now you can see it in the list.

**Comment by naokomc** [comment]
Thank you @StevenDufresne (and sorry about my late reply). That's exactly what we needed to do.
I will add this to our documentation so it won't be missed.

https://make.wordpress.org/community/?p=38812
